# Generated by Django 3.0.4 on 2020-05-10 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('contents', models.TextField(blank=True, default='', null=True)),
                ('created_date', models.DateField(auto_now_add=True, null=True)),
                ('submit_check', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
